.\"Created with GNOME Manpages Editor
.\"http://gmanedit.sourceforge.net
.\"Sergio Rua <srua@gpul.org>
.\"
.TH remuco-xmms2 1 "" "remuco-xmms2"

.SH NAME
remuco-xmms2

.SH SYNOPSIS
.B remuco-xmms2
.br

.SH DESCRIPTION
.B remuco-xmms2
is a player proxy for the Remuco system. At the same time it is a client for the XMMS2 daemon. You can start it manually while XMMS2 is up or create a symlink to it from the user XMMS2 startup directory to let the XMMS2 daemon start it automatically.
.PP

.SH OPTIONS
No options...


.SH FILES

.I $XDG_DATA_HOME/xmms/startup.d
The directory to create a symlink from to the
.B
remuco-xmms2
binary to let XMMS2 automatically start
.B remuco-xmms2

.SH LICENCE
GPLv2

.SH AUTHOR
This manual page was written by Christian Buennig <mondai@users.sourceforge.net>