.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH REMUCO 1 "May 12, 2008" 
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
remuco \- Remuco server control
.SH SYNOPSIS
.B remuco
.RI [ options ] 
.br
.SH DESCRIPTION
.B remuco
is a program to control the Remuco server. Use it to start or stop the server or to get status information about the server.
.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below. If no options are given, status information about the server is shown.
.TP
.B \-?, \-\-help
Show summary of options
.TP
.B \-v, \-\-version
Show version of program
.TP
.B \-o, \-\-stop
Stop the server
.TP
.B \-a, \-\-start
Start the server (if not running already)
.TP
.B \-r, \-\-restart
Restart the server
.TP
.B \-p, \-\-stop-proxy=\fINAME\fP
Stop the player proxy \fINAME\fP
.TP
.B \-d, \-\-debug
Toggle debug mode. Also effects player proxies. Becomes effective on next server start.
.SH FILES
.IP \(bu 2 
.I $XDG_CACHE_HOME/remuco/Server.log
\- server log file
.IP \(bu 2 
.I $XDG_CONFIG_HOME/remuco/Server.conf
\- server configuration
(there should an example configuration in the doc dir)
.IP \(bu 2 
.I $XDG_CACHE_HOME/remuco/NAME.log
\- log file of player proxy \fINAME\fR (not used by all player proxies)
.IP \(bu 2 
.I $XDG_CONFIG_HOME/remuco/debug
\- debug flag (if this file is present, server and player proxies log in debug mode) - the presence of this file can be controlled with option \fI-d\fR
.P
.IP \(bu 2 
.I $XDG_CONFIG_HOME/remuco/*.bpp
\- basic player proxy files
.P
Note: $XDG_CACHE_HOME and $XDG_CONFIG_HOME usually expand to ~/.cache and ~/.config
(see http://standards.freedesktop.org/basedir-spec/).
.SH TROUBLESHOOTING
See \fIDOC_DIR/README\fP.
.SH BUGS
See \fIDOC_DIR/README\fP.
.SH SUPPORT
See \fIDOC_DIR/README\fP.
.SH SEE ALSO
.IP \(bu 2 
.BR remuco-server (1),
.BR remuco-bpp (1)
.IP \(bu 2 
DOC_DIR/README
.IP \(bu 2 
DOC_DIR/Server.conf.example
.IP \(bu 2 
http://remuco.sourceforge.net/
.SH AUTHOR
Oben Sonne <obensonne@googlemail.com>.
.SH HISTORY
2008 \- Initial version.

