.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH REMUCO 1 "May 12, 2008" 
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
remuco-server \- Remuco server
.SH SYNOPSIS
.B remuco-server
.RI [ options ] 
.br
.SH DESCRIPTION
.B remuco-server
is the Remuco server that intermediates between Remuco clients and Remuco player proxies. Do not run this program directly, unless you are debugging (in that case use option '--force'). For regular usage of the server, use the tool
\fBremuco\fP.
.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-?, \-\-help
Show summary of options
.TP
.B \-f, \-\-force
Force manual start
.TP
.B \-l, \-\-log-here
Log to stdout/err
.SH FILES
See \fBremuco (1)\fP.
.SH BUGS
See \fBremuco (1)\fP.
.SH SEE ALSO
.BR remuco (1),
.BR remuco-bpp (1)
.SH AUTHOR
Oben Sonne <obensonne@googlemail.com>.
.SH HISTORY
2008 \- Initial version.

