#!/usr/bin/python

# =============================================================================
#
#    Songbird adapter for Remuco                                                 
#    Copyright (C) 2009 Pawel Szubert <pawel.pbm@gmail.com>                    
#        
#    Remuco - A remote control system for media players.
#    Copyright (C) 2006-2009 Oben Sonne <obensonne@googlemail.com>
#
#    This file is part of Remuco.
#
#    Remuco is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Remuco is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Remuco.  If not, see <http://www.gnu.org/licenses/>.
#
# =============================================================================

"""Remuco player adapter for Songbird, implemented as an executable script."""

import dbus
from dbus.exceptions import DBusException
import gobject

import remuco
from remuco import log

# =============================================================================
# player adapter
# =============================================================================

class SongbirdAdapter(remuco.MPRISAdapter):
    
    def __init__(self):
        
        remuco.MPRISAdapter.__init__(self, "songbird", "Songbird", 
                                     mime_types=("audio",))
        
        self.__am = None
        
    def start(self):
        
        remuco.MPRISAdapter.start(self)
        
        try:
            bus = dbus.SessionBus()
            self.__am = bus.get_object("org.mpris.songbird", "/Player")
        except DBusException, e:
            raise StandardError("dbus error: %s" % e)

    def stop(self):
        
        remuco.MPRISAdapter.stop(self)
        
        self.__am = None
        
    def poll(self):
        remuco.MPRISAdapter.poll(self)
        
    # =========================================================================
    # control interface 
    # =========================================================================
    
    def ctrl_toggle_shuffle(self):
        remuco.MPRISAdapter.ctrl_toggle_shuffle(self)
            
# =============================================================================
# main
# =============================================================================

if __name__ == '__main__':

    pa = SongbirdAdapter()
    mg = remuco.Manager(pa, player_dbus_name="org.mpris.songbird")
    
    mg.run()

