MSG_ID_IGNORE = 0
MSG_ID_SYN_PLIST = 1 # obsolet (player list)
MSG_ID_IFS_PINFO = 2
MSG_ID_SYN_STATE = 3
MSG_ID_SYN_PLOB = 4
MSG_ID_SYN_PLAYLIST = 5
MSG_ID_SYN_QUEUE = 6
MSG_ID_IFS_SRVDOWN = 7
MSG_ID_IFC_CINFO = 8
MSG_ID_SEL_PLAYER = 9 # obsolet
MSG_ID_CTL = 10
MSG_ID_REQ_PLOB = 11
MSG_ID_REQ_LIBRARY = 12

MSG_ID_PRIV_REQ_INITIAL_DATA = 1001 # used internally in server

    