CMD_IGNORE = 0
CMD_PLAYPAUSE = 1
CMD_STOP = 2        # obsolete
CMD_NEXT = 3
CMD_PREV = 4
CMD_JUMP = 5
CMD_SEEK_FWD = 6
CMD_SEEK_BWD = 7
CMD_VOLUME = 8
CMD_RATE = 9
CMD_PLAYNEXT = 10
CMD_SETTAGS = 12
CMD_REPEAT = 13
CMD_SHUFFLE = 14
CMD_SHUTDOWN = 0x0100

