MSG_ID_IGNORE = 0
MSG_ID_PINFO = 2
MSG_ID_STATE = 3
MSG_ID_PLOB = 4
MSG_ID_BYE = 7
MSG_ID_CINFO = 8
MSG_ID_CTRL = 10
MSG_ID_REQ_PLOB = 11
MSG_ID_REQ_LIBRARY = 12

MSG_ID_REQ_INITIAL = 1001 # used internally in server

    