###############################################################################
#
# Targets
#
###############################################################################

all:
	make -C server all
	make -C bpp all

install: 
	make -C server install
	make -C bpp install

uninstall:
	make -C server uninstall
	make -C bpp uninstall
	
clean:
	make -C server clean
	make -C bpp clean
	
