/* Generated by dbus-binding-tool; do not edit! */

#include <glib/gtypes.h>
#include <glib/gerror.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_net_sf_remuco_Shell
#define DBUS_GLIB_CLIENT_WRAPPERS_net_sf_remuco_Shell

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
net_sf_remuco_Shell_ping (DBusGProxy *proxy, GError **error)

{
  return dbus_g_proxy_call (proxy, "Ping", error, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*net_sf_remuco_Shell_ping_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
net_sf_remuco_Shell_ping_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(net_sf_remuco_Shell_ping_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
net_sf_remuco_Shell_ping_async (DBusGProxy *proxy, net_sf_remuco_Shell_ping_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "Ping", net_sf_remuco_Shell_ping_async_callback, stuff, g_free, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
net_sf_remuco_Shell_shutdown (DBusGProxy *proxy, GError **error)

{
  return dbus_g_proxy_call (proxy, "Shutdown", error, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*net_sf_remuco_Shell_shutdown_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
net_sf_remuco_Shell_shutdown_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(net_sf_remuco_Shell_shutdown_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
net_sf_remuco_Shell_shutdown_async (DBusGProxy *proxy, net_sf_remuco_Shell_shutdown_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "Shutdown", net_sf_remuco_Shell_shutdown_async_callback, stuff, g_free, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_net_sf_remuco_Shell */

G_END_DECLS
