all:
	make -C binding-python
	make -C rhythmbox
	make -C xmms2

clean:
	make -C binding-python clean
	make -C rhythmbox clean
	make -C xmms2 clean

dist:
	make -C binding-python dist
	make -C rhythmbox dist
	make -C xmms2 dist

