package remuco.controller;

/**
 * Interface for classes interested in events generated by a
 * {@link CommController}.
 * 
 * @author Christian Buennig
 * 
 * @see CommController#CommController(ICCEventListener)
 * 
 */
public interface ICCEventListener {

	/**
	 * Event: Comm controller currently successfully connected to the device
	 * specified before via {@link CommController#connect(String)}.
	 */
	public static final int EVENT_CONNECTED = 2;

	/**
	 * Event: Comm controller currently tries to connect to the device specified
	 * before via {@link CommController#connect(String)}.
	 */
	public static final int EVENT_CONNECTING = 1;

	/**
	 * Event: Comm controller detected an error which prevents it from
	 * continuing its work.
	 */
	public static final int EVENT_ERROR = 0;

	/**
	 * Notify about an event.
	 * 
	 * @param type
	 *            one of {@link #EVENT_ERROR}, {@link #EVENT_CONNECTING} or
	 *            {@link #EVENT_CONNECTED}.
	 * 
	 * @param msg
	 *            a message decribing the event more detailed, ready to be
	 *            displayed to the user
	 */
	public void event(int type, String msg);

}
